### ISSUE TITLE
歌曲文件似乎没有VBR header

### ISSUE THREAD

**Issue by i0ntempest** [AxeelAnder/DynamixSongInfo#1]
提取出的所有歌曲都是VBR mp3，但是好像没有正确的VBR header，导致播放器无法显示正确的歌曲长度。
![untitled](https://user-images.githubusercontent.com/16017904/46183474-01c3d500-c29f-11e8-91fd-8d03c97eb905.png)
![untitleda](https://user-images.githubusercontent.com/16017904/46183478-04bec580-c29f-11e8-9379-34b45fee6890.png)

**Comment by AxeelAnder** [comment]
改了比特率的参数，现在能显示正确的长度了。今天更新文件(感谢github无限空间)

**Comment by i0ntempest** [comment]
改了之后全都压成128了啊。。。既然无限空间为啥不用256呢（原来的VBR大概平均bitrate在256左右）

**Comment by i0ntempest** [comment]
或者，我不知道C#能不能做到，VBR header是可以被修复的：
`ffmpeg -i file_orig.mp3 -acodec copy file_fixed.mp3`
部分专业播放器（比如fb2k）也可以修复

**Comment by AxeelAnder** [comment]
比较令人失望的是看起来原本的音乐文件就是这个质量(根据文件大小来看)，如果强行提高比特率可能并不会带来音质上的提升
